services:
  velocity:
    env_file: .env.dev
    user: "${UID:-1000}:${GID:-1000}"
    build: ./docker/velocity
    container_name: velocity
    ports:
      - "25565:25565"          # public port → Velocity default
    volumes:
      - ./data/velocity/plugins:/server/plugins
      - ./data/velocity/config:/server         # toml files
    restart: unless-stopped

  paper:
    env_file: .env.dev
    build: ./docker/paper
    user: "${UID:-1000}:${GID:-1000}"
    container_name: paper
    depends_on:
      - mariadb
      - redis
    ports:
      - "25566:25565"          # internal testing; Velocity will connect on 25566
    volumes:
      - ./data/paper:/server
    environment:
      VELOCITY_PORT: 25577     # we’ll read this in paper.yml later
    restart: unless-stopped

  mariadb:
    env_file: .env.dev
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_APP_USER}
      MYSQL_PASSWORD: ${MYSQL_APP_PASS}
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD}"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  flyway:
    env_file: .env.dev
    image: flyway/flyway:10
    volumes:
      - ./infra/sql:/flyway/sql
      - ./infra/flyway.conf:/flyway/conf/flyway.conf
    depends_on:
      mariadb:
        condition: service_healthy
    command: -configFiles=/flyway/conf/flyway.conf migrate
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  redis:
    env_file: .env.dev
    image: redis:7
    command: ["redis-server","--appendonly","yes"]
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  mariadb-data:
  redis-data: