services:
  velocity:
    user: "${UID:-1000}:${GID:-1000}"
    build: ./docker/velocity
    container_name: velocity
    ports:
      - "25565:25565"          # public port → Velocity default
    volumes:
      - ./data/velocity/plugins:/server/plugins
      - ./data/velocity/config:/server         # toml files
    restart: unless-stopped

  paper:
    build: ./docker/paper
    user: "${UID:-1000}:${GID:-1000}"
    container_name: paper
    depends_on:
      - mariadb
      - redis
    ports:
      - "25566:25565"          # internal testing; Velocity will connect on 25566
    volumes:
      - ./data/paper:/server
    environment:
      VELOCITY_PORT: 25577     # we’ll read this in paper.yml later
    restart: unless-stopped

  mariadb:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: sevenday
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:7
    command: ["redis-server","--appendonly","yes"]
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  mariadb-data:
  redis-data: